title: Dana Gillis
tagline: Test tagline.
email: danagillis2@gmail.com

description: 'I am a student.'

url: 'https://danagillis.github.io'
baseurl: ''

permalink: blog/:title

markdown: kramdown

# Syntax highlighting
highlighter: rouge
# Or this if not on GitHub (?):
# kramdown:
  # input: GFM
  # syntax_highlighter: rouge

sass:
  style: :compressed

gems:
  - jekyll-sitemap
